language: cpp
compiler: gcc

compiler: g++-6
env: COMPILER=g++-6

dist: trusty
sudo: required

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - libfreetype6-dev
      - libjpeg-dev
      - libx11-dev
      - libxrandr-dev
      - libxcb1-dev
      - libx11-xcb-dev
      - libxcb-randr0-dev
      - libxcb-image0-dev
      - libgl1-mesa-dev
      - libflac-dev
      - libogg-dev
      - libvorbis-dev
      - libvorbisenc2
      - libvorbisfile3
      - libopenal-dev
      - libpthread-stubs0-dev
      - libglew-dev
      - libgpgme11-dev
      - libsndfile1-dev
      - libudev-dev
      
script:
  - mkdir ~/temp
  - cd ~/temp
  - wget https://cmake.org/files/v3.8/cmake-3.8.2.tar.gz
  - tar xzvf cmake-3.8.2.tar.gz
  - cd cmake-3.8.2/
  - ./bootstrap
  - make -j4 > makelog
  - sudo make install > makelog-install
  - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-6
  - export CXX=/usr/bin/g++-6
  - gcc -v && g++ -v && cmake --version
  - sudo apt-get install libsfml-dev
  - mkdir build
  - cd build
  - cmake ..
  - make
