language: cpp
compiler: gcc
script:
  - sudo apt-get purge cmake
  - mkdir ~/temp && cd ~/temp && wget https://cmake.org/files/v3.8/cmake-3.8.0.tar.gz
  - tar xzvf cmake-3.8.0.tar.gz && cd cmake-3.8.0/
  - ./bootstrap && make -j4 && sudo make install
  - cd .. && rm -rf cmake-3.8.0
  - cmake --version
  - sudo apt-get install libsfml-dev
  - mkdir build
  - cd build
  - cmake ..
  - make
