language: cpp
compiler: gcc

dist: trusty
sudo: required

      
script:
  - sudo add-apt-repository ppa:nschloe/cmake-nightly
  - sudo apt-get update
  - sudo apt-get install cmake
  - cmake --version
  - sudo apt-get install libsfml-dev
  - mkdir build
  - cd build
  - cmake ..
  - make
