language: cpp
compiler: gcc
script:
  - sudo apt-get purge cmake
  - wget https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.sh
  - ./cmake-3.8.2-Linux-x86_64.sh
  - cmake --version
  - sudo apt-get install libsfml-dev
  - mkdir build
  - cd build
  - cmake ..
  - make
