language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - nschloe/cmake-nightly
    packages:
      - cmake
      - cmake-data
      
script:
  - cmake --version
  - sudo apt-get install libsfml-dev
  - mkdir build
  - cd build
  - cmake ..
  - make
