language: cpp
compiler: gcc
script:
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x -y
  - sudo apt-get update
  - sudo apt-get install cmake
  - cmake --version
  - sudo apt-get install libsfml-dev
  - mkdir build
  - cd build
  - cmake ..
  - make
